<?php

$productCollection = $block->getProductListCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$count = $productCollection->count();

?>
<?php if($count): ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
            <?php foreach ($productCollection as $product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($product, 'category_page_grid');
                        ?>
                        <a href="<?= $product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($product, $product->getName(), 'name') ?>
                                </a>
                            </strong>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php else: ?>
     <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php endif; ?>
